### ISSUE TITLE
cudaErrorInvalidConfiguration using a Tesla K40

### ISSUE THREAD

**Issue by HorstSteuer** [ANR-COMPASS/shesha#12]
We have installed shesha on a computer with a Geforce RTX 2080 Ti and a Tesla K40 using CUDA 10.1. The software works as expected on the Geforce, but will fail to compute even the example parameter file from the installation manual when using the K40. There seems to be a bug in the configuration of a CUDA kernel call:

`ipython -i shesha/scripts/closed_loop.py data/par/par4bench/scao_sh_16x16_8pix.py`
```
Doing imat svd...
svd done in 0.181055 s
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/shesha/shesha/scripts/closed_loop.py in <module>
     87         print("Using GENERIC controller...")
     88 
---> 89     supervisor.initConfig()
     90     if arguments["--niter"]:
     91         supervisor.loop(int(arguments["--niter"]), compute_tar_psf=compute_tar_psf)

~/shesha/shesha/supervisor/compassSupervisor.py in initConfig(self)
    293         Initialize the simulation
    294         '''
--> 295         self._sim.init_sim()
    296         self.rtc = self._sim.rtc
    297         self.iter = self._sim.iter

~/shesha/shesha/sim/simulator.py in init_sim(self)
    215         self._wfs_init()
    216 
--> 217         self._rtc_init(ittime)
    218 
    219         self.is_init = True

~/shesha/shesha/sim/simulator.py in _rtc_init(self, ittime)
    292                                 self.config.p_centroiders, self.config.p_controllers,
    293                                 self.config.p_dms, brahma=False,
--> 294                                 dataBase=self.matricesToLoad, use_DB=self.use_DB)
    295         else:
    296             self.rtc = None

~/shesha/shesha/init/rtc_init.py in rtc_init(context, tel, wfs, dms, atmos, p_wfss, p_tel, p_geom, p_atmos, ittime, p_centroiders, p_controllers, p_dms, do_refslp, brahma, cacao, tar, dataBase, use_DB)
    127                                 p_atmos, ittime, p_tel, rtc, dms, wfs, tel, atmos,
    128                                 p_centroiders, do_refslp, dataBase=dataBase,
--> 129                                 use_DB=use_DB)
    130 
    131             # add a geometric controller for processing error breakdown

~/shesha/shesha/init/rtc_init.py in init_controller(context, i, p_controller, p_wfss, p_geom, p_dms, p_atmos, ittime, p_tel, rtc, dms, wfs, tel, atmos, p_centroiders, do_refslp, dataBase, use_DB)
    393         init_controller_ls(i, p_controller, p_wfss, p_geom, p_dms, p_atmos, ittime,
    394                            p_tel, rtc, dms, wfs, tel, atmos, dataBase=dataBase,
--> 395                            use_DB=use_DB)
    396 
    397     if (p_controller.type == scons.ControllerType.CURED):

~/shesha/shesha/init/rtc_init.py in init_controller_ls(i, p_controller, p_wfss, p_geom, p_dms, p_atmos, ittime, p_tel, rtc, dms, wfs, tel, atmos, dataBase, use_DB)
    496     else:
    497         cmats.cmat_init(i, rtc, p_controller, p_wfss, p_atmos, p_tel, p_dms,
--> 498                         nmodes=p_controller.nmodes)
    499 
    500         rtc.d_control[i].set_gain(p_controller.gain)

~/shesha/shesha/ao/cmats.py in cmat_init(ncontrol, rtc, p_controller, p_wfss, p_atmos, p_tel, p_dms, nmodes)
    118             mfilt = np.where((eigenv / eigenv[eigenv.shape[0] - 3]) < 1. / maxcond)[0]
    119         else:
--> 120             mfilt = np.where((1. / (eigenv / eigenv[2])) > maxcond)[0]
    121         nfilt = mfilt.shape[0]
    122 

IndexError: index 2 is out of bounds for axis 0 with size 2
```

Using Nvidia Nsight Compute for Debugging, there seem to be a number of failing calls to `cuModuleGetFunction` and, probably more importantly, several failed `cudaLaunchKernel`:
`cudaLaunchKernel,,cudaErrorInvalidConfiguration(9),"(0x7f8eb83a67e3, {1,1,1}, {1536,1,1}, 0x7fff209e8810{0x7fff209e87c8}, 0, 0x0)"`
This does not happen on the Geforce.

For a different parameter file, and using our slightly modified version of the shesha code, we get a perhaps more helpful error message to locate the error:
 
```

line 163, in imat_init
rtc.do_imat(ncontrol, dms)
RuntimeError: after reduction step 2: cudaErrorInvalidConfiguration: invalid configuration argument
srun: error: gpunode002: task 0: Exited with exit code 1
```

**Comment by a-sevin** [comment]
Thanks Host for your feedback. I'll try to see what's happen but I don'thave access to a K40 to test.

Please, could you tell us which type and version number of compass and shesha do you use ?

**Comment by HorstSteuer** [comment]
Thank you for looking into it! 

I am using shesha on the master branch: commit id 7c0aadbb1bfcf27cd840f399dee39d8cd22575c1

Conda tells me the following on the compass package:
# Name                    Version                   Build  Channel
compass                   4.3.1                   cuda101    compass

**Comment by a-sevin** [comment]
Sorry for the late answer... But it's difficult to debug without any K40 in-house... Keep it in mind

**Comment by a-sevin** [comment]
I released a new version of compass. Could you try to update all:

```bash
conda install -c compass magma compass
cd $SHESHA_ROOT
git pull 
```

Hope this works...

**Comment by HorstSteuer** [comment]
I am afraid it didn't work. I am getting an identical error (except some line numbers changed due to the updated code). Below are the installed packages:
```
compass                   4.3.2                   cuda101    compass
magma                     2.5.2               cuda101.mkl    compass
```

**Comment by a-sevin** [comment]
I don't understand... I think I need an technical account to investigate...

**Comment by a-sevin** [comment]
To prevent any problem on your system, could you try to run this docker image ?

nvidia-docker run -it --rm nvidia/cuda:10.1-devel-ubuntu16.04
(or docker run --gpus all -it --rm nvidia/cuda:10.1-devel-ubuntu16.04 depending of your docker version)
```bash
    apt-get update -y && apt-get upgrade -y && apt-get install -y git wget bzip2
    cd $HOME
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    bash Miniconda3-latest-Linux-x86_64.sh -b
    export PATH=/root/miniconda3/bin:$PATH
    conda install -c compass compass -y
    git clone https://github.com/ANR-COMPASS/shesha.git
    export SHESHA_ROOT=$HOME/shesha
    export PYTHONPATH=$SHESHA_ROOT:$PYTHONPATH
    export PYTHONDONTWRITEBYTECODE=1
    cd $SHESHA_ROOT
    ipython -i shesha/scripts/closed_loop.py data/par/par4bench/scao_sh_16x16_8pix.py

    # if closed_loop.py works : 
    ./tests/checkCompass.sh 
```

**Comment by HorstSteuer** [comment]
I ran `docker run --gpus all -it --rm nvidia/cuda:10.1-devel-centos7` and replaced apt-get with yum. I also added 
`p_loop.set_devices([5])`
to scao_sh_16x16_8pix.py to specify the K40. Using this I still get the same error as the one above. Additionally I get the following error messages:

```
Creating turbulent layers :
  0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]CUBLAS error : Unsupported numerical value was passed to function.
CUBLAS error in /compass/src/miniconda3/conda-bld/compass_1574843314692/work/libcarma/src.cpp/carma_cublas.cpp@518
CUBLAS error : Unsupported numerical value was passed to function.
```
hundreds(?) of times.

```
Pattern type : square
Computing Influence Function type :  default
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 284/284 [00:00<00:00, 420.02it/s]
->target
CUBLAS error : Unsupported numerical value was passed to function.
CUBLAS error in /compass/src/miniconda3/conda-bld/compass_1574843314692/work/libcarma/src.cpp/carma_cublas.cpp@444
CUBLAS error : Unsupported numerical value was passed to function.
CUBLAS error in /compass/src/miniconda3/conda-bld/compass_1574843314692/work/libcarma/src.cpp/carma_cublas.cpp@444
CUBLAS error : Unsupported numerical value was passed to function.
CUBLAS error in /compass/src/miniconda3/conda-bld/compass_1574843314692/work/libcarma/src.cpp/carma_cublas.cpp@179
```

```
Doing imat...

done in 1.8892e-05 s
CUBLAS error : Unsupported numerical value was passed to function.
CUBLAS error in /compass/src/miniconda3/conda-bld/compass_1574843314692/work/libcarma/src.cpp/carma_cublas.cpp@444
CUBLAS error : Unsupported numerical value was passed to function.█████████████████████████                                                                                 | 1/2 [00:00<00:00, 407.568it/s]
CUBLAS error in /compass/src/miniconda3/conda-bld/compass_1574843314692/work/libcarma/src.cpp/carma_cublas.cpp@444
DM1: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 655.554it/s]
done in 0.00310645 s

done in 0.003377 s
Doing imat svd...
CUBLAS error : Unsupported numerical value was passed to function.
CUBLAS error in /compass/src/miniconda3/conda-bld/compass_1574843314692/work/libcarma/src.cpp/carma_cublas.cpp@801
svd done in 0.000217 s

```

When using the 2080Ti, I am getting a lot of CUBLAS error messages as well. I don't see those when running COMPASS without docker.

The tests seem to fail as well, lots of CUBLAS error messages and 0 SR.

**Comment by a-sevin** [comment]
Please, could you try with Ubuntu docker
nvidia/cuda:10.1-devel-ubuntu16.04

I will generate binaries for centos in parallel

**Comment by HorstSteuer** [comment]
Same result for nvidia/cuda:10.1-devel-ubuntu16.04 as for nvidia/cuda:10.1-devel-centos7. Including the CUBLAS errors...

**Comment by a-sevin** [comment]
Using official nvidia docker doesn't work for me too

I generated a package made on centos7. Could you test it ?

```
conda install -c compass/label/centos7 compass -y
git clone https://github.com/ANR-COMPASS/shesha.git
export SHESHA_ROOT=$HOME/shesha
export PYTHONPATH=$SHESHA_ROOT:$PYTHONPATH
export PYTHONDONTWRITEBYTECODE=1
cd $SHESHA_ROOT
ipython -i shesha/scripts/closed_loop.py data/par/par4bench/scao_sh_16x16_8pix.py

# if closed_loop.py works : 
./tests/checkCompass.sh 
```

**Comment by a-sevin** [comment]
Well, I can reproduce all your problems on centos docker and official nvidia docker...
I will make some investigations this week-end. Keep you inform

**Comment by a-sevin** [comment]
I tried around hundred of configurations/compilation flags... without success...
It's very weird but I will be give up ! :)

**Comment by a-sevin** [comment]
the official nvidia docker is a mess...

```
nvidia-docker run -it --rm nvidia/cuda:10.1-devel-ubuntu16.04
[...] copy matrixMulCUBLAS from samples
root@fe3c81048630:/# ./matrixMulCUBLAS 
[Matrix Multiply CUBLAS] - Starting...
GPU Device 0: "Tesla P100-SXM2-16GB" with compute capability 6.0

GPU Device 0: "Tesla P100-SXM2-16GB" with compute capability 6.0

MatrixA(640,480), MatrixB(480,320), MatrixC(640,320)
CUDA error at matrixMulCUBLAS.cpp:255 code=1(CUBLAS_STATUS_NOT_INITIALIZED) "cublasCreate(&handle)" 
Computing result using CUBLAS...root@fe3c81048630:/# 
```

So difficult in this context...

**Comment by a-sevin** [comment]
So... With a correct docker, it's better but, at this time, I cannot generate binaries for cuda 10.1. 
I just generate new ones with cuda 10.2.
Could you try it ? Maybe you need to update your cuda version (or not)

**Comment by a-sevin** [comment]
Please tell me if the version 4.4.0 fix it ?
